L need only be of dimension (N-1). Include description of GERSCH.  S/DLARRB does not currently set INFO, but need to include code to avoid current undefined reference to INFO, but allow for future change